version: '3.1'
services:
  db:
    container_name: realty-zone-db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - app

  backend:
    container_name: realty-zone-backend
    image: przekol/realty-zone:backend
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app_b/
      - /usr/app_b/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app

  frontend:
    container_name: realty-zone-frontend
    image: przekol/realty-zone:frontend
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app_f/
      - /usr/app_f/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - backend
    networks:
      - app


networks:
  app:
    driver: bridge